name: Issue Subscriber

on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  auto-subscribe:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Automation Script
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: llvm/utils/git/
          ref: main

      - name: Setup Automation Script
        working-directory: ./llvm/utils/git/
        run: |
          pip install -r requirements.txt

      - name: Update watchers
        working-directory: ./llvm/utils/git/
        # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        env:
          LABEL_NAME: ${{ github.event.label.name }}
        run: |
          python3 ./github-automation.py \
            --token '${{ secrets.ISSUE_SUBSCRIBER_TOKEN }}' \
            issue-subscriber \
            --issue-number '${{ github.event.issue.number }}' \
            --label-name "$LABEL_NAME"
