name: "Check libc++ generated files"
on:
  pull_request:
    paths:
      - 'libcxx/**'

permissions:
  contents: read

jobs:
  check_generated_files:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Fetch LLVM sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dependencies
        uses: aminya/setup-cpp@d485b24c1283deafc12b4b8ae90ff09c0d1eb972 # v1
        with:
          clangformat: 17.0.1
          ninja: true

      - name: Check generated files
        run: libcxx/utils/ci/run-buildbot check-generated-output
