name: LLVM Bugs notifier

permissions:
  contents: read
  issues: read

on:
  issues:
    types:
      - opened

jobs:
  auto-subscribe:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 18
          check-latest: true
      - run: npm install mailgun.js form-data
      - name: Send notification
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        env:
          MAILGUN_API_KEY: ${{ secrets.LLVM_BUGS_KEY }}
        with:
          script: |
            const Mailgun = require('mailgun.js');
            const formData = require('form-data');

            const mailgun = new Mailgun(formData);
            const DOMAIN = 'email.llvm.org';

            const mg = mailgun.client({ username: 'api', key: process.env.MAILGUN_API_KEY });

            github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })
            .then((issue) => {
              const payload = {
                author : issue.data.user.login,
                issue  : issue.data.number,
                title  : issue.data.title,
                url    : issue.data.html_url,
                labels : issue.data.labels.map((label) => label.name),
                assignee : issue.data.assignees.map((assignee) => assignee.login),
                body   : issue.data.body
              };

              const data = {
                from: 'LLVM Bugs <llvm-bugs@email.llvm.org>',
                to: 'llvm-bugs@lists.llvm.org',
                subject: `[Bug ${issue.data.number}] ${issue.data.title}`,
                template: 'new-github-issue',
                'o:tracking-clicks': 'no',
                'h:X-Mailgun-Variables': JSON.stringify(payload)
              };

              return mg.messages.create(DOMAIN, data);
            })
            .then((msg) => console.log(msg));
