name: Labeling new issues
on:
  issues:
    types: ['opened']

permissions:
  contents: read

jobs:
  automate-issues-labels:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: llvm/actions/issue-labeler@a1ea791b03c8e61f53a0e66f2f73db283aa0f01e # main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/new-issues-labeler.yml
          include-title: 1
          include-body: 0
          sync-labels: 0
          enable-versioned-regex: 0
