name: PR Request Release Note

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types:
      - closed

jobs:
  request-release-note:
    if: >-
      github.repository_owner == 'llvm' &&
      startsWith(github.ref, 'refs/heads/release')

    runs-on: ubuntu-latest
    steps:
      # We need to pull the script from the main branch, so that we ensure
      # we get the latest version of this script.
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Scripts
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            llvm/utils/git/requirements.txt
            llvm/utils/git/github-automation.py
          sparse-checkout-cone-mode: false

      - name: Install Dependencies
        run: |
          pip install -r llvm/utils/git/requirements.txt

      - name: Request Release Note
        env:
          # We need to use an llvmbot token here, because we are mentioning a user.
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python3 llvm/utils/git/github-automation.py \
            --repo "$GITHUB_REPOSITORY" \
            --token "$GITHUB_TOKEN" \
            request-release-note \
            --pr-number ${{ github.event.pull_request.number}}
