name: PR Subscriber

on:
  pull_request_target:
    types:
      - labeled

permissions:
  contents: read

jobs:
  auto-subscribe:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout Automation Script
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: llvm/utils/git/
          ref: main

      - name: Setup Automation Script
        working-directory: ./llvm/utils/git/
        run: |
          pip install -r requirements.txt

      - name: Update watchers
        working-directory: ./llvm/utils/git/
        run: |
          python3 ./github-automation.py \
            --token '${{ secrets.ISSUE_SUBSCRIBER_TOKEN }}' \
            pr-subscriber \
            --issue-number "${{ github.event.number }}" \
            --label-name "${{ github.event.label.name }}"
